### PR TITLE
add stickler file

### PR DESCRIPTION
**Pull request by mekinus**

### CODE REVIEW

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @mekinus  and @TashfeenRao  :wave: 

Nice work; the project is taking sharp but there are few issues to address.

**Bottom part**
- [ ] It contains links to other articles with image previews on the leftmost side. (_Note that these should be links_).
Also, something is messing with your element flow. Please fix it.

review-nyt-more

review-nyt-more-overflow


 **Navigation bar**
* [ ] It should have a fixed position (it sticks to the top part of the screen).

 **Footer**
* [ ] It should have a fixed position (it sticks to the bottom part of the screen).

**Theory of inflation section**
Something is messing with your elements. Please find and squash the bugs.

review-nyt-theory

**Others**
- [ ] Do not push commented code to repos. 
It’s better to delete commented code. If you need to review a previous version of your code, use git history.
https://github.com/mekinus/nyt-clone/blob/8160ff695cda9a1b892a3a7897c36e4fe3354502/index.html#L441

- [ ] You failed to use `float` to align all the elements. I am sorry but this was clearly stated.
review-nyt-use-float
**Please close attention to that `aside` tag requirement too**

- [ ] Stickler checks are failing here. Please fix the errors.

[OPTIONAL]
Consider using lower cases for your directory names. This is just the usual convention.

review-nyt-folder-name


**Please submit another code review after fixing these issues**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Review by KaushikShivam — CHANGES_REQUESTED** [review]
# Status: Changes Required 🔴 

Hello @mekinus & @TashfeenRao  👋 

Great job implementing changes required by the previous TSE. However, there are a couple of things that you need to fix before I can pass your review.

- [ ] Please make sure that you have no stickler errors
- [x] Please make sure that your footer is positioned properly. Right now, it's floating over other elements. Please refer the provided screenshot
Screen Shot 2019-11-05 at 11 49 40 PM
### bottom part (Please refer to the screenshot provided by the previous TSE)
- [ ]  It contains links to other articles with image previews on the leftmost side. (Note that these should be links).
### Navigation bar
- [x] Make sure that items inside the navigation bar are vertically aligned. Refer the screenshot
Screen Shot 2019-11-05 at 11 52 58 PM

- [x]  You failed to use ```float``` to align all the elements. I am sorry but this was clearly stated.

Please make sure that all the items in the checklist are fixed including the ones from the previous TSE and submit another review request.

 ### That's all, guys! 
**Make these changes and submit for a code review, again**

**If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.**

Happy coding! 😄 
[Shivam Kaushik](https://github.com/KaushikShivam)
[Github](https://github.com/KaushikShivam) [Twitter](https://twitter.com/kShivamDev) [Linkedin](https://www.linkedin.com/in/shivam-kaushik-bb8162102/)

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Team!  
#### Wow, your project looks :+1: 
Some Required Changes

#### Bottom part (Please refer to the screenshot provided by the previous TSE)

- [ ] It contains links to other articles with image previews on the leftmost side.(Note that these should be links).



Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by shshamim63** [comment]
### Status :arrow_forward:  Approved!! :tada:  :taco: 
___
Hi @mekinus  and @TashfeenRao  :wave:,
Great job :clap: , All the required part for this project are completed successfully. 
#### This :+1: is from me. You can merge it and don't forget to fill the project completion form.
___
### Happy Coding :herb: 
#### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/) | [Slack](Shakhawat Hossain)

**Pull request merged**
